apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eshop-ingress
  namespace: default
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
      - path: /eshopwebmvc
        pathType: Prefix
        backend:
          service:
            name: eshopwebmvc-service
            port:
              number: 80
      - path: /eshoppublicapi
        pathType: Prefix
        backend:
          service:
            name: eshoppublicapi-service
            port:
              number: 80
      - path: /catalogservice
        pathType: Prefix
        backend:
          service:
            name: catalogservice-service
            port:
              number: 80
      - path: /apigateway
        pathType: Prefix
        backend:
          service:
            name: api-gateway-service
            port:
              number: 80
      - path: /catalog-sqlserver
        pathType: Prefix
        backend:
          service:
            name: catalog-sqlserver-service
            port:
              number: 1433
