additionalArguments:
  - --global.checknewversion=true
  - --global.sendanonymoususage=false
  - --entryPoints.metrics.address=:9100/tcp
  - --entryPoints.traefik.address=:9000/tcp
  - --entryPoints.web.address=:8000/tcp
  - --entryPoints.websecure.address=:8443/tcp
  - --api=true
  - --api.dashboard=true
  - --ping=true
  - --metrics.prometheus=true
  - --metrics.prometheus.entrypoint=metrics
  - --providers.kubernetescrd
  - --providers.kubernetescrd.allowEmptyServices=true
  - --providers.kubernetescrd.allowcrossnamespace=true
  - --providers.kubernetesingress
  - --providers.kubernetesingress.allowEmptyServices=true
  - --entryPoints.websecure.http.tls=true
  - --log.level=INFO

crds:
  enabled: true

providers:
  kubernetesIngress:
    namespaces:
      - "default"
      - "rabbitmq-system" 
