name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy-to-aks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Azure CLI
        uses: azure/CLI@v1
        with:
          version: 2.54.0

      - name: Use Access Token for Azure CLI
        env:
          AZURE_ACCESS_TOKEN: ${{ secrets.AZURE_ACCESS_TOKEN }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: |
          echo "$AZURE_ACCESS_TOKEN" > /tmp/azure_access_token
          az account set --subscription "$AZURE_SUBSCRIPTION_ID"
          az login --identity --access-token $(cat /tmp/azure_access_token)
